" Fetch ~/.vimrc bootstrap

" this has to go first
set nocompatible

" init plugins
source ~/.vim/runcoms/neobundle.vim

" general settings
source ~/.vim/runcoms/general.vim

" gui
source ~/.vim/runcoms/gui.vim

" autocommands
source ~/.vim/runcoms/autocommands.vim

" and mappings
source ~/.vim/runcoms/mappings.vim
