#!/bin/zsh


# stat vim server if not running
if [[ -z $(pgrep vim) ]]
then
  termite -e "vim --servername VIM --remote-tab-silent $@" --name "VIM" &> /dev/null &
else
  vim --servername VIM --remote-tab-silent $@
fi

# vi: ft=zsh
