#!/bin/zsh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

INTERFACE="${1:-eth0}"
LABEL="${2:-E}"

if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" == 'up' ]];
then
  echo "$LABEL"
  echo "$LABEL"
else
  echo "$LABEL"
  echo "$LABEL"
  echo "#666666"
fi
