# ~/.zshrc
# BASED ON: https://github.com/myfreeweb/dotfiles

# #
# Runcoms

. $HOME/.zsh/runcoms/modules.zsh
. $HOME/.zsh/runcoms/opts.zsh
. $HOME/.zsh/runcoms/path.zsh
. $HOME/.zsh/runcoms/completions.zsh
. $HOME/.zsh/runcoms/history.zsh
. $HOME/.zsh/runcoms/exports.zsh
. $HOME/.zsh/runcoms/keybindings.zsh
. $HOME/.zsh/runcoms/zfunctions.zsh

# #
# Plugins
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-history-substring-search/zsh-history-substring-search.zsh
[[ -z $BASE16_SCHEME ]] && export BASE16_SCHEME=twilight
local BASE16_SHELL=~/.zsh/base16-shell/base16-$BASE16_SCHEME.dark.sh
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
source /etc/profile.d/autojump.zsh
source $HOME/.zsh/k/k.sh

# #
# Prompt
autoload -U promptinit && promptinit
prompt pure

# #
# Aliases
source ~/.zsh/runcoms/aliases.zsh
